[package]
name = "fluentbit-rustwasmfilter"
version = "0.1.0"
edition = "2021"

[lib]
# Fluentbit WASM filters have to be built as a library that function names
# are searched for within
crate-type = ["cdylib"]
path = "src/wasmfilter.rs"

[dependencies]
rmp = "0.8.14"
rmpv = "1.3.0"

[profile.dev]
opt-level = 1
